server:
  port: 10100
  servlet:
    context-path: /sc-oauth
  use-forward-headers: true

spring:
  application:
    name: sc-oauth
  redis:
    host: localhost
    port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka
  instance:
    prefer-ip-address: true