server:
  port: 10500
  servlet:
    context-path: /sc-user
  use-forward-headers: true


spring:
  application:
    name: sc-user
  datasource:
    driver-class-name: org.h2.Driver
    schema: classpath:db/schema-*.sql
    data: classpath:db/data-*.sql
    url: jdbc:h2:mem:test
    username: root
    password: root



eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka
  instance:
    prefer-ip-address: true


mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0