server:
  port: 10003
  servlet:
    context-path: /sc-user
  use-forward-headers: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka
  instance:
    prefer-ip-address: true

spring:
  application:
    name: sc-user
