server:
  port: 10510
  servlet:
    context-path: /sc-order


spring:
  application:
    name: sc-order


eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka
  instance:
    prefer-ip-address: true
