spring:
  application:
    name: sc-zuul

server:
  port: 10010

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka/
zuul:
  routes:
    sc-user:
      path: /sc-user/**
      serviceId: sc-user
      strip-prefix: false
      custom-sensitive-headers: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000  #设置API网关中路由转发请求的HystrixCommand执行超时时间
ribbon:
  ConnectTimeout: 3000 #设置路由转发请求的时候，创建请求连接的超时时间
  ReadTimeout: 60000  #用来设置路由转发请求的超时时间