server:
  port: 10020

spring:
  application:
    name: sc-gateway
  cloud:
    loadbalancer:
      ribbon:
        # 关闭 LoadBalancerClientFilter，使用 ReactiveLoadBalancerClientFilter
        enabled: false
    gateway:
      # 跨域配置
      globalcors:
        cors-configurations:
          '[/**]':
            allowCredentials: true
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      # 全局超时配置
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s


eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka/


management:
  endpoints:
    web:
      exposure:
        #开放所有页面节点  默认只开启了health、info两个节点
        include: "*"