server:
  port: 10020

spring:
  application:
    name: sc-gateway
  cloud:
    gateway:
      routes:
        - id: sc-user-websocket
          uri: lb://sc-user
          predicates:
            - Path=/sc-user/websocket/**
        - id: sc-user
          uri: lb://sc-user
          predicates:
            - Path=/sc-user/**



eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka/