server:
  port: 1004

spring:
  application:
    name: sc-gateway
  cloud:
    gateway:
      routes:
        - id: sc-user
          uri: lb://sc-user
          predicates:
            - Path=/sc-user/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka/